### ISSUE TITLE
如何使用

### ISSUE THREAD

**Issue by ZENG-YUN-FEI** [BigBrotherTrade/trader#2]
对于这些代码，不知道如何配置，是需要trade和中央控制台什么都下载吗，下载后是软件形式还是什么，是需要有python和c++多种形式吗

**Comment by timercrack** [comment]
这个问题太基础了。。你得先懂得python和C++程序如何运行的才能使用它。

**Comment by ZENG-YUN-FEI** [comment]
好的，感谢您的回复。我目前还是一名学生，对于量化非常感兴趣。现在刚刚学完python不久，请问看懂您的程序还需要学习c++吗。在能够懂得如何运行后可以直接部署至我的电脑吗






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BigBrotherTrade/trader"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月4日(星期四) 中午12:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BigBrotherTrade/trader] 如何使用 (Issue #2)





 
这个问题太基础了。。你得先懂得python和C++程序如何运行的才能使用它。
