### ISSUE TITLE
缺少config.ini文件，请问下这个文件怎么写呀？

### ISSUE THREAD

**Issue by 505088376** [BigBrotherTrade/trader#3]
<img width="953" alt="988c9ad9bb0f20332d9a0f7c534afe8" src="https://github.com/BigBrotherTrade/trader/assets/44466631/5da461a1-6497-48d3-9c6d-543ba9c3b6d8">
运行 main文件时候，报了这个错  应该是我没有config.ini配置文件，拿不到那个secret_key  请问该怎么处理呢？

**Comment by timercrack** [comment]
[看这个文件](https://github.com/BigBrotherTrade/trader/blob/master/trader/utils/read_config.py)

**Comment by ylsaker** [comment]
@505088376 请问你解决了吗？ @timercrack 上面的文件没有关于DJANGO的配置呀？

**Comment by ghLcd9dG** [comment]
config.ini template 
```
[MSG_CHANNEL]
request_pattern = MSG:CTP:REQ:*
request_format = MSG:CTP:REQ:{}
trade_response_prefix = MSG:CTP:RSP:TRADE:
trade_response_format = MSG:CTP:RSP:TRADE:{}:{}
market_response_prefix = MSG:CTP:RSP:MARKET:
market_response_format = MSG:CTP:RSP:MARKET:{}:{}
weixin_log = MSG:LOG:WEIXIN

[TRADE]
command_timeout = 5
ignore_inst = WH,bb,JR,RI,RS,LR,PM,im

[REDIS]
host = 127.0.0.1
port = 6379
db = 0
encoding = utf-8

[MYSQL]
host = 127.0.0.1
port = 3306
db = QuantDB
user = quant
password = 123456

[QuantDL]
api_key = 123456

[Tushare]
token = 123456

[LOG]
level = DEBUG
format = %(asctime)s %(name)s [%(levelname)s] %(message)s
weixin_format = [%(levelname)s] %(message)s

[DJANGO]
secret_key = your_secret_key_here
debug = True  # or False, depending on your environment
allowed_hosts = *
```

**Comment by bluemeteorolite** [comment]
试了一下,临时方案，以mac为例子：
（1）brew install redis & mysql, and make sure they are up, and make sure you have python3 + installled
  (2) secret_key ， search a secret key generation website
  (3) change settings.py - caches node, location = 127.0.0.1.6379 - this is to connect redis for cach
  (4) run python manage.py run sever, good luck to start dashboard

**Comment by smartpeanut** [comment]
按上面的模板编写了config.ini后，执行提示No option 'connect_string' in section: 'REDIS'。如果我在[REDIS] section手动添加connect_string字段，会提示ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject。

请问该如何解决 @timercrack
